site_name: Konan LLM

theme:
  name: 'material'
  logo: 'images/CI.png'
  favicon: 'images/favicon.ico'
  font:
    text: Noto Sans KR
    code: Roboto Mono
  palette:
    primary: '#00008B'  # deep blue 대신 유효한 색상 코드 사용
    accent: '#00008B'
  
nav:
  - Konan LLM: index.md          # 메인 페이지
  - Ver 1.0:
      - 개요: v 1.0/개요.md   
      - 모델 관리: v 1.0/모델 관리.md 
      - 프롬프트 갤러리: v 1.0/프롬프트 갤러리.md
      - 추가 학습: v 1.0/추가 학습.md
      - 미세 조정: v 1.0/미세 조정.md
      - 플레이 그라운드: v 1.0/플레이 그라운드.md
      - 프롬프트 설계: v 1.0/프롬프트 설계.md
      - 검색증강생성(RAG): v 1.0/검색증강생성(RAG).md
  - Ver 2.0:
      - 개요: v 2.0/개요.md   
      - 모델 관리: v 2.0/모델 관리.md 
      - 프롬프트 갤러리: v 2.0/프롬프트 갤러리.md
      - 추가 학습: v 2.0/추가 학습.md
      - 미세 조정: v 2.0/미세 조정.md
      - 플레이 그라운드: v 2.0/플레이 그라운드.md
      - 프롬프트 설계: v 2.0/프롬프트 설계.md
      - 검색증강생성(RAG): v 2.0/검색증강생성(RAG).md      
extra:
  generator: false

extra_css:
  - extra.css

plugins:
  - search
  - with-pdf:
      cover: true
      cover_logo: docs/images/logo.png
      cover_title: 'Konan LLM'
#      cover_subtitle: "Ver. 1.0"      
      output_path: 'PDF_folder/Konan-LLM_1.0.pdf'
      author: 'Konan Technology'
      custom_template_path: templates